version: "3.7"
services:

  mvcapp:
    image: cicdmvc
    ports: 
      - "8090:80"
    build: .
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
  integration:
    image: cicdit
    build: CICD.IntegrationTests/.
