// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WBA.PE2.KurbanovD.Web.Data;

namespace WBA.PE2.KurbanovD.Web.Migrations
{
    [DbContext(typeof(CardGameContext))]
    [Migration("20200605180430_AddSummonUnitToEffectMigration")]
    partial class AddSummonUnitToEffectMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.CardUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Armor");

                    b.Property<double>("Damage");

                    b.Property<int>("DamageType");

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<double>("Health");

                    b.Property<double>("HealthRegen");

                    b.Property<string>("Img");

                    b.Property<double>("Mana");

                    b.Property<double>("Manaregen");

                    b.Property<string>("Name");

                    b.Property<int>("Race");

                    b.HasKey("Id");

                    b.ToTable("CardUnits");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CardUnit");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("EffectType");

                    b.Property<Guid?>("SummonUnitId1");

                    b.HasKey("Id");

                    b.HasIndex("SummonUnitId1");

                    b.ToTable("Effects");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Effect");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.HeroItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Img");

                    b.Property<string>("Name");

                    b.Property<Guid?>("SkillId");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("HeroItems");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.CardUnitSkills", b =>
                {
                    b.Property<Guid>("CardUnitId");

                    b.Property<Guid>("SkillId");

                    b.HasKey("CardUnitId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillSets");

                    b.HasData(
                        new { CardUnitId = new Guid("6f68fcfd-7cd6-4410-bc35-b7d96aa23969"), SkillId = new Guid("dd027abc-a8b9-4d89-b582-41c480c4fb45") },
                        new { CardUnitId = new Guid("6f68fcfd-7cd6-4410-bc35-b7d96aa23969"), SkillId = new Guid("e5e7bd4c-2be6-411c-a75c-81b4a8db86c3") },
                        new { CardUnitId = new Guid("038a0497-bf84-45cd-8fcc-22fd78bcafe1"), SkillId = new Guid("62ea4143-f6f3-4390-ac72-3e23561ed06b") },
                        new { CardUnitId = new Guid("038a0497-bf84-45cd-8fcc-22fd78bcafe1"), SkillId = new Guid("9bffe083-6bee-4a99-adcc-7d6cfbc8b59b") },
                        new { CardUnitId = new Guid("f6620430-3d02-4bae-9802-066434d03668"), SkillId = new Guid("f600f388-352a-4674-a533-1cc1347b7d61") },
                        new { CardUnitId = new Guid("f6620430-3d02-4bae-9802-066434d03668"), SkillId = new Guid("c68ed6dd-0479-47cb-810c-03e897990665") },
                        new { CardUnitId = new Guid("66e9be55-ffef-438a-9203-64a7a3062af7"), SkillId = new Guid("eb1d8e33-1cad-4f14-98c3-72938bad25fd") },
                        new { CardUnitId = new Guid("66e9be55-ffef-438a-9203-64a7a3062af7"), SkillId = new Guid("6ac2049f-151e-40bb-899e-0e836e0b6f5c") },
                        new { CardUnitId = new Guid("7129011f-bca0-4449-9629-3a46198267a1"), SkillId = new Guid("c03d9352-b51b-4d56-afe4-dfb2a32158a2") },
                        new { CardUnitId = new Guid("7129011f-bca0-4449-9629-3a46198267a1"), SkillId = new Guid("7ebeac14-4fac-4afb-9dc0-24fdc0c2fe39") },
                        new { CardUnitId = new Guid("e618edeb-ba86-449a-9602-896adb2db850"), SkillId = new Guid("147c6bc2-4e9b-4afc-b422-e0130252b1e0") },
                        new { CardUnitId = new Guid("e618edeb-ba86-449a-9602-896adb2db850"), SkillId = new Guid("cc4610f6-4f20-41d1-a529-522636674ff6") },
                        new { CardUnitId = new Guid("27f53ca1-3a40-4462-961d-d860547d8417"), SkillId = new Guid("8fb27632-30c5-4e4b-9925-c3594fe55c5a") },
                        new { CardUnitId = new Guid("484c6ca0-42c8-42ec-80ed-c919ef6f186c"), SkillId = new Guid("36478d6b-ac61-4c5a-af51-c649ff8851d2") },
                        new { CardUnitId = new Guid("484c6ca0-42c8-42ec-80ed-c919ef6f186c"), SkillId = new Guid("9572a874-9e78-4f3d-9964-5a25daf101d3") },
                        new { CardUnitId = new Guid("deb26782-8dd4-4d8e-9016-1202138b7b59"), SkillId = new Guid("c3414818-5b50-4da6-94e4-129339ccc21b") },
                        new { CardUnitId = new Guid("deb26782-8dd4-4d8e-9016-1202138b7b59"), SkillId = new Guid("b783a6d3-af5b-4b10-9f53-f3b05eb84aaf") },
                        new { CardUnitId = new Guid("b3c06915-0178-42de-a9bb-4369a41acfac"), SkillId = new Guid("eb1d8e33-1cad-4f14-98c3-72938bad25fd") },
                        new { CardUnitId = new Guid("b3c06915-0178-42de-a9bb-4369a41acfac"), SkillId = new Guid("00f75578-175e-40be-82b3-71e558041981") },
                        new { CardUnitId = new Guid("cc45d15c-a24a-4e04-9720-8e1e7841f6b4"), SkillId = new Guid("c6be27f6-3217-400f-9427-499d5719a5b6") },
                        new { CardUnitId = new Guid("cc45d15c-a24a-4e04-9720-8e1e7841f6b4"), SkillId = new Guid("7e4656e2-1440-46ee-a5e9-2438e359f33b") },
                        new { CardUnitId = new Guid("f9678bc4-bfe5-4bd9-a333-a0a93e943baa"), SkillId = new Guid("3a1a8de1-43b7-4dbe-861d-9c635e83df85") },
                        new { CardUnitId = new Guid("f9678bc4-bfe5-4bd9-a333-a0a93e943baa"), SkillId = new Guid("50fe62bf-979a-4ee7-9f12-b5313e00de98") },
                        new { CardUnitId = new Guid("9cae91c6-5213-4447-a4b3-458c2e4dd944"), SkillId = new Guid("4db2ba57-6f02-4c95-bf0a-f59af269fd3f") },
                        new { CardUnitId = new Guid("9cae91c6-5213-4447-a4b3-458c2e4dd944"), SkillId = new Guid("8fb27632-30c5-4e4b-9925-c3594fe55c5a") }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.SkillEffects", b =>
                {
                    b.Property<Guid>("SkillId");

                    b.Property<Guid>("EffectId");

                    b.Property<Guid>("TargetId");

                    b.HasKey("SkillId", "EffectId", "TargetId");

                    b.HasIndex("EffectId");

                    b.HasIndex("TargetId");

                    b.ToTable("SkillEffects");

                    b.HasData(
                        new { SkillId = new Guid("f600f388-352a-4674-a533-1cc1347b7d61"), EffectId = new Guid("eebe8f58-962c-4a81-8d9a-ea9c0b63d9d7"), TargetId = new Guid("46e167dc-52ad-4fbe-9950-967f55dc19c8") },
                        new { SkillId = new Guid("f600f388-352a-4674-a533-1cc1347b7d61"), EffectId = new Guid("03f7e71e-1729-4b24-a192-90c0470d83ed"), TargetId = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3") },
                        new { SkillId = new Guid("6ac2049f-151e-40bb-899e-0e836e0b6f5c"), EffectId = new Guid("16b9e7ba-239d-4c5b-a337-f3f78fff8065"), TargetId = new Guid("fb50a816-cd8d-4fd1-ba38-bf277dee7a1e") },
                        new { SkillId = new Guid("6ac2049f-151e-40bb-899e-0e836e0b6f5c"), EffectId = new Guid("44c83bc1-ecf8-4d19-b2cf-c608dcb4fe6a"), TargetId = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3") },
                        new { SkillId = new Guid("50fe62bf-979a-4ee7-9f12-b5313e00de98"), EffectId = new Guid("a4d29024-307a-4a9b-8fe1-8db09421d73a"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("50fe62bf-979a-4ee7-9f12-b5313e00de98"), EffectId = new Guid("1c021dbd-16a9-4146-b810-ff1d36211599"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("29c6ba61-a08f-4e32-9d46-77aa6c8f1478"), EffectId = new Guid("c5abb22c-394a-41a4-a1b7-df2ef3dfebc1"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("29c6ba61-a08f-4e32-9d46-77aa6c8f1478"), EffectId = new Guid("621a5b22-fcd1-43d5-9a5f-c3d35f6c631e"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("36478d6b-ac61-4c5a-af51-c649ff8851d2"), EffectId = new Guid("d436f5e5-d729-4d24-be7b-52e235b3bda8"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("87e38d0b-af62-439a-8cfa-febc53ac1b01"), EffectId = new Guid("ec381dc9-c1e5-47fb-8c57-51678224f07f"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("87e38d0b-af62-439a-8cfa-febc53ac1b01"), EffectId = new Guid("c5abb22c-394a-41a4-a1b7-df2ef3dfebc1"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("b783a6d3-af5b-4b10-9f53-f3b05eb84aaf"), EffectId = new Guid("915f8f7d-2a9d-4995-ae89-9d6f6e7bb40d"), TargetId = new Guid("7f0c2aa1-42ca-4b97-8371-7e7821a4a745") },
                        new { SkillId = new Guid("62ea4143-f6f3-4390-ac72-3e23561ed06b"), EffectId = new Guid("0feb5631-dd56-44b2-a207-00ee33551f09"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("62ea4143-f6f3-4390-ac72-3e23561ed06b"), EffectId = new Guid("1deaa57c-bc65-485e-8bb1-8d69aeeffa3d"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("9bffe083-6bee-4a99-adcc-7d6cfbc8b59b"), EffectId = new Guid("10076a8f-db65-4226-b910-cf6059cbe8d1"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("9bffe083-6bee-4a99-adcc-7d6cfbc8b59b"), EffectId = new Guid("ec381dc9-c1e5-47fb-8c57-51678224f07f"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("69bfd9cd-6c36-4637-8f17-6951cacb1204"), EffectId = new Guid("a4d29024-307a-4a9b-8fe1-8db09421d73a"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("cc4610f6-4f20-41d1-a529-522636674ff6"), EffectId = new Guid("a0c92644-5852-4a0d-884f-f27ca162fa0e"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("85d9908a-f79d-4586-9637-91c9de70983c"), EffectId = new Guid("ecaee0cf-bafa-4f21-8e6d-2e5fbd3cfe87"), TargetId = new Guid("799d2e51-f05c-4975-8a2b-99ddfeb8d9ca") },
                        new { SkillId = new Guid("8fb27632-30c5-4e4b-9925-c3594fe55c5a"), EffectId = new Guid("826bcba5-228b-4685-b454-5b233e2cd036"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("c3414818-5b50-4da6-94e4-129339ccc21b"), EffectId = new Guid("b12bbe16-3e81-4500-abb9-625f88e384f5"), TargetId = new Guid("636e0bb8-2876-4072-814f-1ab11e732e6c") },
                        new { SkillId = new Guid("c68ed6dd-0479-47cb-810c-03e897990665"), EffectId = new Guid("0feb5631-dd56-44b2-a207-00ee33551f09"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("c68ed6dd-0479-47cb-810c-03e897990665"), EffectId = new Guid("b1c4dd1a-d2cc-4f16-842e-c5b99bfcb4bd"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("dd027abc-a8b9-4d89-b582-41c480c4fb45"), EffectId = new Guid("460be20d-f644-4bc2-9286-7ead03b64e9c"), TargetId = new Guid("636e0bb8-2876-4072-814f-1ab11e732e6c") },
                        new { SkillId = new Guid("f50ade16-3b0e-4de4-af15-f268f075dd78"), EffectId = new Guid("874a9cf7-9719-4bbf-8e7f-30b4c77712e4"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("f50ade16-3b0e-4de4-af15-f268f075dd78"), EffectId = new Guid("d818f097-d830-4b3b-aaec-5abc73d5be59"), TargetId = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3") },
                        new { SkillId = new Guid("35c69f01-7c39-4324-aa6f-d550676229ad"), EffectId = new Guid("d5bd4c65-41a0-4bdc-a155-30d3d343b774"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("7ebeac14-4fac-4afb-9dc0-24fdc0c2fe39"), EffectId = new Guid("64e1a36b-d705-468f-8bfd-58d60d01a9a8"), TargetId = new Guid("646aa733-f4cf-4392-a339-2a067044d787") },
                        new { SkillId = new Guid("147c6bc2-4e9b-4afc-b422-e0130252b1e0"), EffectId = new Guid("15332b71-72f5-45b8-9027-263ce0328067"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("9572a874-9e78-4f3d-9964-5a25daf101d3"), EffectId = new Guid("3e8534bc-9679-4380-9034-1b9d62d6b8f5"), TargetId = new Guid("fb50a816-cd8d-4fd1-ba38-bf277dee7a1e") },
                        new { SkillId = new Guid("fc3e01a3-f6db-4912-b95c-ae10a4bc6832"), EffectId = new Guid("621a5b22-fcd1-43d5-9a5f-c3d35f6c631e"), TargetId = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3") },
                        new { SkillId = new Guid("fc3e01a3-f6db-4912-b95c-ae10a4bc6832"), EffectId = new Guid("265e0345-f383-4ac8-b33c-a4e20ee05faa"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("c03d9352-b51b-4d56-afe4-dfb2a32158a2"), EffectId = new Guid("85c2344e-22d7-42e2-aced-84c35c8eb13c"), TargetId = new Guid("a73a283d-a5fd-46cf-a95f-c03b05473295") },
                        new { SkillId = new Guid("7e4656e2-1440-46ee-a5e9-2438e359f33b"), EffectId = new Guid("16b9e7ba-239d-4c5b-a337-f3f78fff8065"), TargetId = new Guid("13d0b53a-c6ad-425c-a8c1-be7ae118e78a") },
                        new { SkillId = new Guid("c6be27f6-3217-400f-9427-499d5719a5b6"), EffectId = new Guid("80e4330a-1ec5-498d-b3b9-eb74cef24775"), TargetId = new Guid("13d0b53a-c6ad-425c-a8c1-be7ae118e78a") },
                        new { SkillId = new Guid("00f75578-175e-40be-82b3-71e558041981"), EffectId = new Guid("1deaa57c-bc65-485e-8bb1-8d69aeeffa3d"), TargetId = new Guid("952d3a54-9c70-4c2b-a657-20d077a62238") },
                        new { SkillId = new Guid("eb1d8e33-1cad-4f14-98c3-72938bad25fd"), EffectId = new Guid("1deaa57c-bc65-485e-8bb1-8d69aeeffa3d"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("6d241033-20da-4d9d-88db-d38551007304"), EffectId = new Guid("1a78deb7-c5d1-43de-be46-5945153a6aca"), TargetId = new Guid("253acb52-d5c6-4cd6-a8f8-974be5b6a91d") },
                        new { SkillId = new Guid("18ef20f2-b94d-4a3f-b38e-60d247a4c627"), EffectId = new Guid("aba933fd-0da7-41aa-a4fb-19e9f6a4e86e"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("18ef20f2-b94d-4a3f-b38e-60d247a4c627"), EffectId = new Guid("783a580c-8153-457c-847f-4e137c7e9b44"), TargetId = new Guid("a73a283d-a5fd-46cf-a95f-c03b05473295") },
                        new { SkillId = new Guid("e5e7bd4c-2be6-411c-a75c-81b4a8db86c3"), EffectId = new Guid("3e8534bc-9679-4380-9034-1b9d62d6b8f5"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("4db2ba57-6f02-4c95-bf0a-f59af269fd3f"), EffectId = new Guid("25b2142f-ad42-4f4c-9c3e-855e465b28a6"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("3a1a8de1-43b7-4dbe-861d-9c635e83df85"), EffectId = new Guid("64e1a36b-d705-468f-8bfd-58d60d01a9a8"), TargetId = new Guid("0faafc79-6a2c-4506-b68a-d5c9ce226bdc") },
                        new { SkillId = new Guid("3a1a8de1-43b7-4dbe-861d-9c635e83df85"), EffectId = new Guid("04b17411-2761-465b-84cf-ac0e3589073d"), TargetId = new Guid("0faafc79-6a2c-4506-b68a-d5c9ce226bdc") }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.UserHeroCards", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("HeroId");

                    b.HasKey("UserId", "HeroId");

                    b.HasIndex("HeroId");

                    b.ToTable("UserHeroCards");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Img");

                    b.Property<string>("Name");

                    b.Property<int>("Skillsort");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Skill");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("HeroTargetType");

                    b.Property<int>("TargetType");

                    b.HasKey("Id");

                    b.ToTable("Targets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Target");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthenticationToken");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = new Guid("caa41c5f-5325-40d0-984e-bb8a65603015"), AuthenticationToken = new Guid("00000000-0000-0000-0000-000000000000"), CreationDate = new DateTime(2020, 6, 5, 20, 4, 30, 116, DateTimeKind.Local), FirstName = "Agent", LastName = "FourtySeven", Password = "770150d66c470890da86f7fdf85af234", Role = 0, UserName = "BaldnessIsGrace" },
                        new { Id = new Guid("39bddd9e-f602-4f6f-8f33-22c11f867ed1"), AuthenticationToken = new Guid("00000000-0000-0000-0000-000000000000"), CreationDate = new DateTime(2020, 6, 5, 20, 4, 30, 118, DateTimeKind.Local), FirstName = "Gaben", LastName = "Newell", Password = "dc1d5ad33491a9aa8eae91c4f968ad24", Role = 1, UserName = "AllHailTheKing" }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Units.Hero", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.CardUnit");

                    b.Property<int>("ActionPoints");

                    b.Property<int>("HeroClass");

                    b.ToTable("Hero");

                    b.HasDiscriminator().HasValue("Hero");

                    b.HasData(
                        new { Id = new Guid("6f68fcfd-7cd6-4410-bc35-b7d96aa23969"), Armor = 5.0, Damage = 95.0, DamageType = 0, Description = "When the hunted tell tales of Gondar the Bounty Hunter, none are sure of which are true. In whispered tones they say he was abandoned as a kit, learning his skill in tracking as a matter of simple survival. Others hear he was an orphan of war, taken in by the great Soruq the Hunter to learn the master's skill with a blade as they plumbed the dark forests for big game. Still others believe he was a lowly street urchin raised among a guild of cutpurses and thieves, trained in the arts of stealth and misdirection. Around campfires in the wild countryside his quarry speaks the rumors of Gondar's work, growing ever more fearful: they say it was he who tracked down the tyrant King Goff years after the mad regent went into hiding, delivering his head and scepter as proof. That it was he who infiltrated the rebel camps at Highseat, finally bringing the legendary thief White Cape to be judged for his crimes. And that it was he who ended the career of Soruq the Hunter, condemned as a criminal for killing the Prince's prized hellkite. The tales of Gondar's incredible skill stretch on, with each daring feat more unbelievable than the last, each target more elusive. For the right price, the hunted know, anyone can be found. For the right price, even the mightiest may find fear in the shadows.", Health = 300.0, HealthRegen = 25.0, Img = "BountyHunter.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Bounty Hunter", Race = 3, ActionPoints = 2, HeroClass = 4 },
                        new { Id = new Guid("038a0497-bf84-45cd-8fcc-22fd78bcafe1"), Armor = 8.0, Damage = 75.0, DamageType = 2, Description = "The veteran of countless battles on a thousand worlds, Chaos Knight hails from a far upstream plane where the fundamental laws of the universe have found sentient expression. Of all the ancient Fundamentals, he is the oldest and most tireless, endlessly searching out a being he knows only as \"The Light.\" Long ago the Light ventured out from the progenitor realm, in defiance of the first covenant. Now Chaos Knight shifts from plane to plane, always on the hunt to extinguish the Light wherever he finds it. A thousand times he has snuffed out the source, and always he slides into another plane to continue his search anew. Upon his steed Armageddon he rides, wading into battle with maniacal frenzy, drawing strength from the disorder of the universe. A physical manifestation of chaos itself, in times of need he calls upon other versions of himself from other planes, and together these dark horsemen ride into battle, as unstoppable as any force of nature. Only when the last Light of the world is scoured from existence will the search be ended. Where rides the Chaos Knight, death soon follows.", Health = 600.0, HealthRegen = 35.0, Img = "ChaosKnight.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Chaos Knight", Race = 1, ActionPoints = 4, HeroClass = 5 },
                        new { Id = new Guid("f6620430-3d02-4bae-9802-066434d03668"), Armor = 3.0, Damage = 35.0, DamageType = 1, Description = "Born in a temperate realm, raised with her fiery older sister Lina, Rylai the Crystal Maiden soon found that her innate elemental affinity to ice created trouble for all those around her. Wellsprings and mountain rivers froze in moments if she stopped to rest nearby; ripening crops were bitten by frost, and fruiting orchards turned to mazes of ice and came crashing down, spoiled. When their exasperated parents packed Lina off to the equator, Rylai found herself banished to the cold northern realm of Icewrack, where she was taken in by an Ice Wizard who had carved himself a hermitage at the crown of the Blueheart Glacier. After long study, the wizard pronounced her ready for solitary practice and left her to take his place, descending into the glacier to hibernate for a thousand years. Her mastery of the Frozen Arts has only deepened since that time, and now her skills are unmatched.", Health = 300.0, HealthRegen = 15.0, Img = "CrystalMaiden.jpg", Mana = 5.0, Manaregen = 1.0, Name = "Crystal Maiden", Race = 0, ActionPoints = 1, HeroClass = 6 },
                        new { Id = new Guid("66e9be55-ffef-438a-9203-64a7a3062af7"), Armor = 5.0, Damage = 45.0, DamageType = 0, Description = "Each young acolyte to the Dezun order must complete a series of rites before becoming a shadow priest. The final rite, the rite of shades, is a harrowing spiritual journey through the Nothl Realm, an unpredictable domain from which not all visitants return. Of those who do, some return mad. Others return with strange aptitudes. But all who go there are changed by their experiences. Driven by the need for enlightenment, Dazzle was the youngest of his tribe ever to request the sacred ritual. At first the order refused him, saying he was too young. But Dazzle was not to be dissuaded. Sensing something special in the headstrong young acolyte, the elders relented. Dazzle drank down the sacred potion and sat by the fire while the rest of his tribe danced through the night. In this ethereal dimension of the Nothl Realm, the properties of light and dark are inverted. Thus his brilliant healing light, beautiful to our eye, is actually a sinister kind of evil; and the darkest deeds are done in a dazzling glow. The elders' intuition was prophetic: Dazzle returned to his people as a Shadow Priest like none seen before, with the power to heal as well as to destroy. Now he uses his gift to fight his enemies and help his friends.", Health = 450.0, HealthRegen = 50.0, Img = "Dazzle.jpg", Mana = 3.0, Manaregen = 1.0, Name = "Dazzle", Race = 5, ActionPoints = 3, HeroClass = 7 },
                        new { Id = new Guid("7129011f-bca0-4449-9629-3a46198267a1"), Armor = 2.0, Damage = 75.0, DamageType = 0, Description = "Drow Ranger's given name is Traxex--a name well suited to the short, trollish, rather repulsive Drow people. But Traxex herself is not a Drow. Her parents were travelers in a caravan set upon by bandits, whose noisy slaughter of innocents roused the ire of the quiet Drow people. After the battle settled, the Drow discovered a small girl-child hiding in the ruined wagons, and agreed she could not be abandoned. Even as child, Traxex showed herself naturally adept at the arts they prized: Stealth, silence, subtlety. In spirit, if not in physique, she might have been a Drow changeling, returned to her proper home. But as she grew, she towered above her family and came to think of herself as ugly. After all, her features were smooth and symmetrical, entirely devoid of warts and coarse whiskers. Estranged from her adopted tribe, she withdrew to live alone in the woods. Lost travelers who find their way from the forest sometimes speak of an impossibly beautiful Ranger who peered at them from deep among the trees, then vanished like a dream before they could approach. Lithe and stealthy, icy hot, she moves like mist in silence. That whispering you hear is her frozen arrows finding an enemy's heart.", Health = 300.0, HealthRegen = 20.0, Img = "DrowRanger.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Drow Ranger", Race = 4, ActionPoints = 1, HeroClass = 0 },
                        new { Id = new Guid("e618edeb-ba86-449a-9602-896adb2db850"), Armor = 4.0, Damage = 55.0, DamageType = 0, Description = "Aiushtha appears to be an innocent, carefree creature of the woods, and while this is certainly true, it is hardly the sum of her story. She well understands the suffering of the natural world. She has wandered far, and fared through forests bright and drear, in every clime and every season, gathering friends, sharing news, bringing laughter and healing wherever she goes. For in worlds wracked by war, forests are leveled for the building of ships and siege engines; and even in places of peace, the woods are stripped for the building of homes, and as fuel for countless hearths. Aiushtha hears the pleas of the small creatures, the furtive folk who need green shade and a leafy canopy to thrive. She lends her ears to those who have no other listeners. She carries their stories from the wood to the world, believing that her own good cheer is a kind of Enchantment, that can itself fulfill the promise of a verdant future.", Health = 300.0, HealthRegen = 15.0, Img = "Enchantress.jpg", Mana = 5.0, Manaregen = 1.0, Name = "Enchantress", Race = 3, ActionPoints = 1, HeroClass = 7 },
                        new { Id = new Guid("484c6ca0-42c8-42ec-80ed-c919ef6f186c"), Armor = 5.0, Damage = 60.0, DamageType = 0, Description = "No one has ever seen the face hidden beneath the mask of Yurnero the Juggernaut. It is only speculation that he even has one. For defying a corrupt lord, Yurnero was exiled from the ancient Isle of Masks--a punishment that saved his life. The isle soon after vanished beneath the waves in a night of vengeful magic. He alone remains to carry on the Isle's long Juggernaut tradition, one of ritual and swordplay. The last practitioner of the art, Yurnero's confidence and courage are the result of endless practice; his inventive bladework proves that he has never stopped challenging himself. Still, his motives are as unreadable as his expression. For a hero who has lost everything twice over, he fights as if victory is a foregone conclusion.", Health = 600.0, HealthRegen = 25.0, Img = "Juggernaut.jpg", Mana = 4.0, Manaregen = 0.5, Name = "Juggernaut", Race = 0, ActionPoints = 3, HeroClass = 1 },
                        new { Id = new Guid("deb26782-8dd4-4d8e-9016-1202138b7b59"), Armor = 3.0, Damage = 45.0, DamageType = 1, Description = "In life, the frost-mage Ethreain (not yet a Lich) had used the threat of destructive ice to enslave entire kingdoms. His subjects, aided by a few desperate magicians, eventually grew bold enough to ambush him. Armed with enough charmed rope to bind him forever, they tied the frost mage to adamant weights and dropped him in a pool known chiefly for being bottomless. It wasn't. He only fell for a year or so before an outcrop snagged him. There he rested, dead but undecaying, until the geomancer Anhil thought to verify the legend of the supposedly bottomless Black Pool. Anhil's plumbline snarled with the ropes that bound the drowned magician, and up he hauled an unexpected prize. Thinking that by rendering the dead undead, he could question the Lich about the properties of the pool, he removed the bindings and commenced a simple rite of resurrection. Even the descendants of Ethreain's enemies were long forgotten by time, so there were none to warn Anhil against imprudence. But he learned the error of his judgment almost immediately, as Lich threw off the shackles and consumed him.", Health = 450.0, HealthRegen = 25.0, Img = "Lich.jpg", Mana = 6.0, Manaregen = 2.0, Name = "Lich", Race = 4, ActionPoints = 2, HeroClass = 6 },
                        new { Id = new Guid("b3c06915-0178-42de-a9bb-4369a41acfac"), Armor = 1.0, Damage = 60.0, DamageType = 2, Description = "The Ecclesiast-King of Elze nursed a desire for pain — forbidden pain. In a less prominent political figure, such desires might be considered unwise, but in a monarch of his stature, to satisfy such thirsts would have threatened the virtue of the Divine Throne itself. Therefore he turned to his dungeon full of demonologists, promising freedom to whoever could summon a personal succubus of torment and bind it entirely to his service. The creature who arrived, Akasha by name, visited upon him such exquisite torments that he named her his Secret Queen, and he began to spend all his spare moments submitting to her clever torments—eventually abdicating all his responsibilities in his pursuit of the painful pleasures that only she could bring. Queen of Pain could bring him to the brink of death, but she was rune-bound to keep him alive. At last the King's neglect of state brought on an uprising. He was dragged from his chamber and hurled from the Tower of Invocations, and at the moment of death, Queen of Pain was let loose into the world, freed from servitude—freed to visit her sufferings on anyone she deigned to notice.", Health = 400.0, HealthRegen = 10.0, Img = "QueenOfPain.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Queen Of Pain", Race = 1, ActionPoints = 3, HeroClass = 4 },
                        new { Id = new Guid("cc45d15c-a24a-4e04-9720-8e1e7841f6b4"), Armor = 3.0, Damage = 65.0, DamageType = 2, Description = "It is said that Nevermore the Shadow Fiend has the soul of a poet, and in fact he has thousands of them. Over the ages he has claimed the souls of poets, priests, emperors, beggars, slaves, philosophers, criminals and (naturally) heroes; no sort of soul escapes him. What he does with them is unknown. No one has ever peered into the Abysm whence Nevermore reaches out like an eel from among astral rocks. Does he devour them one after another? Does he mount them along the halls of an eldritch temple, or pickle the souls in necromantic brine? Is he merely a puppet, pushed through the dimensional rift by a demonic puppeteer? Such is his evil, so intense his aura of darkness, that no rational mind may penetrate it. Of course, if you really want to know where the stolen souls go, there's one sure way to find out: Add your soul to his collection. Or just wait for Nevermore.", Health = 400.0, HealthRegen = 10.0, Img = "ShadowFiend.jpg", Mana = 5.0, Manaregen = 0.5, Name = "Shadow Fiend", Race = 1, ActionPoints = 5, HeroClass = 2 },
                        new { Id = new Guid("f9678bc4-bfe5-4bd9-a333-a0a93e943baa"), Armor = 12.0, Damage = 85.0, DamageType = 0, Description = "It's an easy thing to offend a troll. A prickly and contentious race, trolls thrive on argument and strife, missing no excuse to raise their voices in dispute. Males grow to maturity in subterranean chambers beneath their matriarch's domicile, feeding and amusing themselves while contributing nothing. Often they stay for years beyond the age of maturity, while the matriarch provides them with sustenance. When young trolls are finally pushed from their sub-chamber, they gather with others of their kind, forming roving gangs of malcontents who complain loudly about all manner of vexation. As much as trolls love to argue, imagine how rare it is for a troll to be driven from his own kind for being too difficult to get along with. Such was Jah'rakal's fate, a monger troll from deep in the Hoven. So deluded was he, so bitter and abrasive, that even other trolls found his company intolerable. After one particularly vitriolic outburst in which he claimed the lion's share of loot from their latest raid, his cohorts finally snapped. They turned on him, beat him with clubs, and drove him from the encampment. Enraged at his banishment, he returned the next day, armed with steel, and slew them all, one by one. He then swore a blood oath: he would ever after be a fighting force unto himself. Now he roams the world as the Troll Warlord, bitter and angry, the Imperial high commander of an army of one.", Health = 650.0, HealthRegen = 50.0, Img = "TrollWarlord.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Troll Warlord", Race = 5, ActionPoints = 4, HeroClass = 1 },
                        new { Id = new Guid("9cae91c6-5213-4447-a4b3-458c2e4dd944"), Armor = 6.0, Damage = 75.0, DamageType = 0, Description = "It had been a brawl to remember. There stood Ymir, the Tusk, the Terror from the Barrier, the Snowball from Cobalt, the only fighter to have bested the Bristled Bruiser in a fair fight, and now the last man standing in Wolfsden Tavern. What started as a simple bar bet of supremacy ended with four regulars, a blacksmith, and six of the Frost Brigade's best soldiers writhing against the shards and splinters of almost every bottle, mug, and chair in the building. The Tusk boasted and toasted his victory as he emptied his brew. No sooner had the defeated regained consciousness than the cries for double-or-nothing rang out. The Tusk was pleased at the prospect, but none could think of a bet bigger than the one he just conquered. Horrified at the damage to his tavern and desperate to avoid another brawl, the barkeep had an idea. As skilled as he was, Ymir had never taken part in a real battle, never tested himself against the indiscriminate death and chaos of war. He proposed a wager to the fighter: seek out the biggest battle he could find, survive, and win it for whichever side he chose. The stakes? The next round of drinks.", Health = 550.0, HealthRegen = 45.0, Img = "Tusk.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Tusk", Race = 3, ActionPoints = 2, HeroClass = 1 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Units.SummonUnit", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.CardUnit");


                    b.ToTable("SummonUnit");

                    b.HasDiscriminator().HasValue("SummonUnit");

                    b.HasData(
                        new { Id = new Guid("27f53ca1-3a40-4462-961d-d860547d8417"), Armor = 5.0, Damage = 1.0, DamageType = 0, Description = "", Health = 100.0, HealthRegen = 25.0, Img = "FearfulSigil.jpg", Mana = 1.0, Manaregen = 1.0, Name = "Fearful Sigil", Race = 7 },
                        new { Id = new Guid("dedb8175-0d78-4644-9ec9-eb0a7b8315a4"), Armor = 5.0, Damage = 1.0, DamageType = 0, Description = "", Health = 100.0, HealthRegen = 25.0, Img = "Nature'sAttendant.jpg", Mana = 1.0, Manaregen = 1.0, Name = "Nature's Attendant", Race = 6 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Amplify", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("Amount");

                    b.Property<int>("AmplifyType");

                    b.Property<int>("EffectState");

                    b.ToTable("Amplify");

                    b.HasDiscriminator().HasValue("Amplify");

                    b.HasData(
                        new { Id = new Guid("44c83bc1-ecf8-4d19-b2cf-c608dcb4fe6a"), Description = "", EffectType = 0, Amount = 5.0, AmplifyType = 5, EffectState = 0 },
                        new { Id = new Guid("b12bbe16-3e81-4500-abb9-625f88e384f5"), Description = "", EffectType = 0, Amount = 10.0, AmplifyType = 5, EffectState = 0 },
                        new { Id = new Guid("265e0345-f383-4ac8-b33c-a4e20ee05faa"), Description = "", EffectType = 0, Amount = 20.0, AmplifyType = 5, EffectState = 0 },
                        new { Id = new Guid("85c2344e-22d7-42e2-aced-84c35c8eb13c"), Description = "", EffectType = 0, Amount = 15.0, AmplifyType = 0, EffectState = 0 },
                        new { Id = new Guid("783a580c-8153-457c-847f-4e137c7e9b44"), Description = "", EffectType = 0, Amount = 25.0, AmplifyType = 0, EffectState = 0 },
                        new { Id = new Guid("a4d29024-307a-4a9b-8fe1-8db09421d73a"), Description = "", EffectType = 0, Amount = 50.0, AmplifyType = 0, EffectState = 0 },
                        new { Id = new Guid("715f2754-f78d-441f-9b94-4bc0946b1e67"), Description = "", EffectType = 0, Amount = 100.0, AmplifyType = 0, EffectState = 0 },
                        new { Id = new Guid("621a5b22-fcd1-43d5-9a5f-c3d35f6c631e"), Description = "", EffectType = 0, Amount = 250.0, AmplifyType = 1, EffectState = 0 },
                        new { Id = new Guid("0079b4f4-a17b-4326-ba40-f2e9753f0b23"), Description = "", EffectType = 0, Amount = 500.0, AmplifyType = 1, EffectState = 0 },
                        new { Id = new Guid("874a9cf7-9719-4bbf-8e7f-30b4c77712e4"), Description = "", EffectType = 0, Amount = 25.0, AmplifyType = 2, EffectState = 0 },
                        new { Id = new Guid("c5abb22c-394a-41a4-a1b7-df2ef3dfebc1"), Description = "", EffectType = 0, Amount = 50.0, AmplifyType = 2, EffectState = 0 },
                        new { Id = new Guid("f7f13521-0089-4759-9873-ebe96c46b4ca"), Description = "", EffectType = 0, Amount = 100.0, AmplifyType = 2, EffectState = 0 },
                        new { Id = new Guid("03f7e71e-1729-4b24-a192-90c0470d83ed"), Description = "", EffectType = 0, Amount = 5.0, AmplifyType = 3, EffectState = 0 },
                        new { Id = new Guid("df2f81c9-54cc-4ddf-ae55-eb59a664aa30"), Description = "", EffectType = 0, Amount = 10.0, AmplifyType = 3, EffectState = 0 },
                        new { Id = new Guid("d818f097-d830-4b3b-aaec-5abc73d5be59"), Description = "", EffectType = 0, Amount = 1.0, AmplifyType = 4, EffectState = 0 },
                        new { Id = new Guid("eebe8f58-962c-4a81-8d9a-ea9c0b63d9d7"), Description = "", EffectType = 0, Amount = 1.5, AmplifyType = 4, EffectState = 0 },
                        new { Id = new Guid("efbbfc8a-6bd7-46a8-8587-455005778bb4"), Description = "", EffectType = 0, Amount = 3.0, AmplifyType = 4, EffectState = 0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.CriticalHit", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("CriticalMultiplier");

                    b.Property<double>("CriticalProcChance");

                    b.Property<int>("DamageType");

                    b.ToTable("CriticalHit");

                    b.HasDiscriminator().HasValue("CriticalHit");

                    b.HasData(
                        new { Id = new Guid("aba933fd-0da7-41aa-a4fb-19e9f6a4e86e"), Description = "", EffectType = 3, CriticalMultiplier = 2.0, CriticalProcChance = 0.2, DamageType = 0 },
                        new { Id = new Guid("b5c330f2-23b4-4bf2-9481-55099367269c"), Description = "", EffectType = 3, CriticalMultiplier = 4.0, CriticalProcChance = 0.2, DamageType = 0 },
                        new { Id = new Guid("10076a8f-db65-4226-b910-cf6059cbe8d1"), Description = "", EffectType = 3, CriticalMultiplier = 4.0, CriticalProcChance = 0.2, DamageType = 2 },
                        new { Id = new Guid("d5bd4c65-41a0-4bdc-a155-30d3d343b774"), Description = "", EffectType = 3, CriticalMultiplier = 2.5, CriticalProcChance = 0.25, DamageType = 0 },
                        new { Id = new Guid("d436f5e5-d729-4d24-be7b-52e235b3bda8"), Description = "", EffectType = 3, CriticalMultiplier = 2.0, CriticalProcChance = 0.3, DamageType = 0 },
                        new { Id = new Guid("25b2142f-ad42-4f4c-9c3e-855e465b28a6"), Description = "", EffectType = 3, CriticalMultiplier = 2.5, CriticalProcChance = 1.0, DamageType = 0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.DealDamage", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("DamageAmount");

                    b.Property<int>("DamageType")
                        .HasColumnName("DealDamage_DamageType");

                    b.ToTable("DealDamage");

                    b.HasDiscriminator().HasValue("DealDamage");

                    b.HasData(
                        new { Id = new Guid("64e1a36b-d705-468f-8bfd-58d60d01a9a8"), Description = "", EffectType = 2, DamageAmount = 100.0, DamageType = 0 },
                        new { Id = new Guid("b1c4dd1a-d2cc-4f16-842e-c5b99bfcb4bd"), Description = "", EffectType = 2, DamageAmount = 150.0, DamageType = 1 },
                        new { Id = new Guid("1deaa57c-bc65-485e-8bb1-8d69aeeffa3d"), Description = "", EffectType = 2, DamageAmount = 150.0, DamageType = 2 },
                        new { Id = new Guid("80e4330a-1ec5-498d-b3b9-eb74cef24775"), Description = "", EffectType = 2, DamageAmount = 200.0, DamageType = 2 },
                        new { Id = new Guid("1dacb3a7-21f4-4439-b23d-c1e693084ee4"), Description = "", EffectType = 2, DamageAmount = 200.0, DamageType = 1 },
                        new { Id = new Guid("915f8f7d-2a9d-4995-ae89-9d6f6e7bb40d"), Description = "", EffectType = 2, DamageAmount = 300.0, DamageType = 1 },
                        new { Id = new Guid("e5af0d52-5663-44f2-b537-dace6d117229"), Description = "", EffectType = 2, DamageAmount = 300.0, DamageType = 2 },
                        new { Id = new Guid("3e8534bc-9679-4380-9034-1b9d62d6b8f5"), Description = "", EffectType = 2, DamageAmount = 300.0, DamageType = 0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Heal", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("HealAmount");

                    b.ToTable("Heal");

                    b.HasDiscriminator().HasValue("Heal");

                    b.HasData(
                        new { Id = new Guid("460be20d-f644-4bc2-9286-7ead03b64e9c"), Description = "", EffectType = 1, HealAmount = 75.0 },
                        new { Id = new Guid("1a78deb7-c5d1-43de-be46-5945153a6aca"), Description = "", EffectType = 1, HealAmount = 150.0 },
                        new { Id = new Guid("2d81259f-a7eb-4fa8-bfdb-613f93e6a9a4"), Description = "", EffectType = 1, HealAmount = 300.0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Lifesteal", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("LifeStealPercentage");

                    b.ToTable("Lifesteal");

                    b.HasDiscriminator().HasValue("Lifesteal");

                    b.HasData(
                        new { Id = new Guid("ec381dc9-c1e5-47fb-8c57-51678224f07f"), Description = "", EffectType = 6, LifeStealPercentage = 0.25 },
                        new { Id = new Guid("55301e2e-9fb6-42cb-9973-498dc910fab1"), Description = "", EffectType = 6, LifeStealPercentage = 0.5 },
                        new { Id = new Guid("1c021dbd-16a9-4146-b810-ff1d36211599"), Description = "", EffectType = 6, LifeStealPercentage = 1.0 },
                        new { Id = new Guid("72ef6e9f-23a9-41c5-817d-3ba44b6ffc5f"), Description = "", EffectType = 6, LifeStealPercentage = 3.0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Reduce", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<int>("EffectState")
                        .HasColumnName("Reduce_EffectState");

                    b.Property<double>("ReduceAmount");

                    b.Property<int>("ReduceType");

                    b.ToTable("Reduce");

                    b.HasDiscriminator().HasValue("Reduce");

                    b.HasData(
                        new { Id = new Guid("16b9e7ba-239d-4c5b-a337-f3f78fff8065"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 5.0, ReduceType = 5 },
                        new { Id = new Guid("04b17411-2761-465b-84cf-ac0e3589073d"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 10.0, ReduceType = 5 },
                        new { Id = new Guid("6634567a-136f-4c81-af40-7b08aba8e5f4"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 15.0, ReduceType = 5 },
                        new { Id = new Guid("ecaee0cf-bafa-4f21-8e6d-2e5fbd3cfe87"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 50.0, ReduceType = 0 },
                        new { Id = new Guid("9faee829-0506-4e85-9892-decee6915dba"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 200.0, ReduceType = 1 },
                        new { Id = new Guid("b0c0f122-5310-4e9d-b809-c5727a6a11b0"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 400.0, ReduceType = 1 },
                        new { Id = new Guid("fddacf94-fb30-4476-be90-6c9ecd14c9c2"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 50.0, ReduceType = 2 },
                        new { Id = new Guid("16bde603-b191-4d96-a7fd-f5fb4609e357"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 100.0, ReduceType = 2 },
                        new { Id = new Guid("3fff91e9-8452-488f-bd23-26d3d308ab14"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 5.0, ReduceType = 3 },
                        new { Id = new Guid("8ed07187-66df-4d46-b1a0-1bdeb8dbacc8"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 1.5, ReduceType = 4 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Silence", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<int>("EffectState")
                        .HasColumnName("Silence_EffectState");

                    b.Property<double>("SilenceDuration");

                    b.ToTable("Silence");

                    b.HasDiscriminator().HasValue("Silence");

                    b.HasData(
                        new { Id = new Guid("c650314d-e527-43ce-9932-5a6b01e7e309"), Description = "", EffectType = 4, EffectState = 1, SilenceDuration = 2.0 },
                        new { Id = new Guid("0025b00d-bbae-47ea-9d0d-e47f5c72ff3d"), Description = "", EffectType = 4, EffectState = 1, SilenceDuration = 4.0 },
                        new { Id = new Guid("f44a84c3-c6eb-42ec-9bb7-c69d9b6abdc0"), Description = "", EffectType = 4, EffectState = 1, SilenceDuration = 6.0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Stun", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<int>("EffectState")
                        .HasColumnName("Stun_EffectState");

                    b.Property<double>("StunDuration");

                    b.ToTable("Stun");

                    b.HasDiscriminator().HasValue("Stun");

                    b.HasData(
                        new { Id = new Guid("0feb5631-dd56-44b2-a207-00ee33551f09"), Description = "", EffectType = 7, EffectState = 1, StunDuration = 2.0 },
                        new { Id = new Guid("a0c92644-5852-4a0d-884f-f27ca162fa0e"), Description = "", EffectType = 7, EffectState = 1, StunDuration = 3.0 },
                        new { Id = new Guid("f7a3978f-30de-4d76-b087-e5146c788b6b"), Description = "", EffectType = 7, EffectState = 1, StunDuration = 4.0 },
                        new { Id = new Guid("4c7c8b0a-5409-41f9-a97d-00f3c7abc45b"), Description = "", EffectType = 7, EffectState = 1, StunDuration = 6.0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Summon", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<int>("AmountToSummon");

                    b.Property<Guid?>("SummonUnitId");

                    b.HasIndex("SummonUnitId");

                    b.ToTable("Summon");

                    b.HasDiscriminator().HasValue("Summon");

                    b.HasData(
                        new { Id = new Guid("826bcba5-228b-4685-b454-5b233e2cd036"), Description = "", EffectType = 5, AmountToSummon = 1, SummonUnitId = new Guid("27f53ca1-3a40-4462-961d-d860547d8417") },
                        new { Id = new Guid("15332b71-72f5-45b8-9027-263ce0328067"), Description = "", EffectType = 5, AmountToSummon = 7, SummonUnitId = new Guid("dedb8175-0d78-4644-9ec9-eb0a7b8315a4") }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Skills.ActiveSkill", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Skill");

                    b.Property<double>("Manacost");

                    b.ToTable("ActiveSkill");

                    b.HasDiscriminator().HasValue("ActiveSkill");

                    b.HasData(
                        new { Id = new Guid("50fe62bf-979a-4ee7-9f12-b5313e00de98"), Img = "BattleTrance.jpg", Name = "Battle Trance", Skillsort = 0, Manacost = 3.0 },
                        new { Id = new Guid("b783a6d3-af5b-4b10-9f53-f3b05eb84aaf"), Img = "ChainFrost.jpg", Name = "Chain Frost", Skillsort = 0, Manacost = 5.0 },
                        new { Id = new Guid("62ea4143-f6f3-4390-ac72-3e23561ed06b"), Img = "ChaosBolt.jpg", Name = "Chaos Bolt", Skillsort = 0, Manacost = 2.5 },
                        new { Id = new Guid("cc4610f6-4f20-41d1-a529-522636674ff6"), Img = "Enchant.jpg", Name = "Enchant", Skillsort = 0, Manacost = 2.0 },
                        new { Id = new Guid("8fb27632-30c5-4e4b-9925-c3594fe55c5a"), Img = "FearfulSigil.jpg", Name = "Fearful Sigil", Skillsort = 0, Manacost = 2.5 },
                        new { Id = new Guid("c3414818-5b50-4da6-94e4-129339ccc21b"), Img = "FrostArmor.jpg", Name = "Frost Armor", Skillsort = 0, Manacost = 2.0 },
                        new { Id = new Guid("c68ed6dd-0479-47cb-810c-03e897990665"), Img = "Frostbite.jpg", Name = "Frostbite", Skillsort = 0, Manacost = 3.0 },
                        new { Id = new Guid("147c6bc2-4e9b-4afc-b422-e0130252b1e0"), Img = "Nature'sAttendants.jpg", Name = "Nature's Attendants", Skillsort = 0, Manacost = 3.0 },
                        new { Id = new Guid("9572a874-9e78-4f3d-9964-5a25daf101d3"), Img = "Omnislash.jpg", Name = "Omnislash", Skillsort = 0, Manacost = 4.5 },
                        new { Id = new Guid("c03d9352-b51b-4d56-afe4-dfb2a32158a2"), Img = "PrecisionAura.jpg", Name = "Precision Aura", Skillsort = 0, Manacost = 2.0 },
                        new { Id = new Guid("c6be27f6-3217-400f-9427-499d5719a5b6"), Img = "RequiemOfSouls.jpg", Name = "Requiem Of Souls", Skillsort = 0, Manacost = 5.0 },
                        new { Id = new Guid("00f75578-175e-40be-82b3-71e558041981"), Img = "ScreamOfPain.jpg", Name = "Scream Of Pain", Skillsort = 0, Manacost = 2.5 },
                        new { Id = new Guid("eb1d8e33-1cad-4f14-98c3-72938bad25fd"), Img = "ShadowStrike.jpg", Name = "Shadow Strike", Skillsort = 0, Manacost = 1.5 },
                        new { Id = new Guid("6d241033-20da-4d9d-88db-d38551007304"), Img = "ShadowWave.jpg", Name = "Shadow Wave", Skillsort = 0, Manacost = 3.5 },
                        new { Id = new Guid("e5e7bd4c-2be6-411c-a75c-81b4a8db86c3"), Img = "ShurikenToss.jpg", Name = "Shuriken Toss", Skillsort = 0, Manacost = 2.5 },
                        new { Id = new Guid("4db2ba57-6f02-4c95-bf0a-f59af269fd3f"), Img = "WalrusPunch.jpg", Name = "Walrus Punch", Skillsort = 0, Manacost = 2.0 },
                        new { Id = new Guid("3a1a8de1-43b7-4dbe-861d-9c635e83df85"), Img = "WhirlingAxes.jpg", Name = "Whirling Axes", Skillsort = 0, Manacost = 2.5 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Skills.PassiveSkill", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Skill");


                    b.ToTable("PassiveSkill");

                    b.HasDiscriminator().HasValue("PassiveSkill");

                    b.HasData(
                        new { Id = new Guid("f600f388-352a-4674-a533-1cc1347b7d61"), Img = "ArcaneAura.jpg", Name = "Arcane Aura", Skillsort = 1 },
                        new { Id = new Guid("6ac2049f-151e-40bb-899e-0e836e0b6f5c"), Img = "BadJuju.jpg", Name = "Bad Juju", Skillsort = 1 },
                        new { Id = new Guid("29c6ba61-a08f-4e32-9d46-77aa6c8f1478"), Img = "BeautifulInside.jpg", Name = "Beautiful Inside", Skillsort = 1 },
                        new { Id = new Guid("36478d6b-ac61-4c5a-af51-c649ff8851d2"), Img = "BladeDance.jpg", Name = "Blade Dance", Skillsort = 1 },
                        new { Id = new Guid("87e38d0b-af62-439a-8cfa-febc53ac1b01"), Img = "BonAppetit.jpg", Name = "Bon Appetit", Skillsort = 1 },
                        new { Id = new Guid("9bffe083-6bee-4a99-adcc-7d6cfbc8b59b"), Img = "ChaosStrike.jpg", Name = "Chaos Strike", Skillsort = 1 },
                        new { Id = new Guid("69bfd9cd-6c36-4637-8f17-6951cacb1204"), Img = "DemonicAttack.jpg", Name = "Demonic Attack", Skillsort = 1 },
                        new { Id = new Guid("85d9908a-f79d-4586-9637-91c9de70983c"), Img = "FearfulAura.jpg", Name = "Fearful Aura", Skillsort = 1 },
                        new { Id = new Guid("dd027abc-a8b9-4d89-b582-41c480c4fb45"), Img = "HealingAttendant.jpg", Name = "Healing Attendant", Skillsort = 1 },
                        new { Id = new Guid("f50ade16-3b0e-4de4-af15-f268f075dd78"), Img = "HumanMind.jpg", Name = "Human Mind", Skillsort = 1 },
                        new { Id = new Guid("35c69f01-7c39-4324-aa6f-d550676229ad"), Img = "Jinada.jpg", Name = "Jinada", Skillsort = 1 },
                        new { Id = new Guid("7ebeac14-4fac-4afb-9dc0-24fdc0c2fe39"), Img = "Marksmanship.jpg", Name = "Marksmanship", Skillsort = 1 },
                        new { Id = new Guid("fc3e01a3-f6db-4912-b95c-ae10a4bc6832"), Img = "Orc'sFlesh.jpg", Name = "Orc's Flesh", Skillsort = 1 },
                        new { Id = new Guid("7e4656e2-1440-46ee-a5e9-2438e359f33b"), Img = "PresenceOfTheDarkLord.jpg", Name = "Presence Of The Dark Lord", Skillsort = 1 },
                        new { Id = new Guid("18ef20f2-b94d-4a3f-b38e-60d247a4c627"), Img = "SharpPaw.jpg", Name = "Sharp Paw", Skillsort = 1 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Targets.MultipleTarget", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Target");

                    b.Property<int>("AmountOfTargets");

                    b.Property<int>("AreaOfEffect");

                    b.ToTable("MultipleTarget");

                    b.HasDiscriminator().HasValue("MultipleTarget");

                    b.HasData(
                        new { Id = new Guid("646aa733-f4cf-4392-a339-2a067044d787"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 2, AreaOfEffect = 1 },
                        new { Id = new Guid("907b6938-1c4c-45dd-aa5c-c6be1c6965de"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 1 },
                        new { Id = new Guid("fb50a816-cd8d-4fd1-ba38-bf277dee7a1e"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 3 },
                        new { Id = new Guid("7f0c2aa1-42ca-4b97-8371-7e7821a4a745"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 5 },
                        new { Id = new Guid("952d3a54-9c70-4c2b-a657-20d077a62238"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 4, AreaOfEffect = 2 },
                        new { Id = new Guid("799d2e51-f05c-4975-8a2b-99ddfeb8d9ca"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 5, AreaOfEffect = 1 },
                        new { Id = new Guid("13d0b53a-c6ad-425c-a8c1-be7ae118e78a"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 99, AreaOfEffect = 99 },
                        new { Id = new Guid("11c5b5e5-60a7-4093-9c45-d3bb0acdb1df"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 1 },
                        new { Id = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 3 },
                        new { Id = new Guid("253acb52-d5c6-4cd6-a8f8-974be5b6a91d"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 5, AreaOfEffect = 4 },
                        new { Id = new Guid("46e167dc-52ad-4fbe-9950-967f55dc19c8"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 5, AreaOfEffect = 4 },
                        new { Id = new Guid("0faafc79-6a2c-4506-b68a-d5c9ce226bdc"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 5, AreaOfEffect = 1 },
                        new { Id = new Guid("a73a283d-a5fd-46cf-a95f-c03b05473295"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 99, AreaOfEffect = 99 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Targets.SingleTarget", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Target");


                    b.ToTable("SingleTarget");

                    b.HasDiscriminator().HasValue("SingleTarget");

                    b.HasData(
                        new { Id = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9"), HeroTargetType = 2, TargetType = 1 },
                        new { Id = new Guid("636e0bb8-2876-4072-814f-1ab11e732e6c"), HeroTargetType = 1, TargetType = 1 },
                        new { Id = new Guid("375b43ef-65db-4b38-9708-66977db44e87"), HeroTargetType = 0, TargetType = 1 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effect", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Units.SummonUnit")
                        .WithMany("Effects")
                        .HasForeignKey("SummonUnitId1");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.HeroItem", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.CardUnitSkills", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.CardUnit", "CardUnit")
                        .WithMany("SkillSet")
                        .HasForeignKey("CardUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Skill", "Skill")
                        .WithMany("CardUnits")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.SkillEffects", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Effect", "Effect")
                        .WithMany("Skills")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Skill", "Skill")
                        .WithMany("Effects")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Target", "Target")
                        .WithMany("SkillEffects")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.UserHeroCards", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Units.Hero", "Hero")
                        .WithMany("Users")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.User", "User")
                        .WithMany("HeroCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Summon", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Units.SummonUnit", "SummonUnit")
                        .WithMany()
                        .HasForeignKey("SummonUnitId");
                });
#pragma warning restore 612, 618
        }
    }
}
