// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WBA.PE2.KurbanovD.Web.Data;

namespace WBA.PE2.KurbanovD.Web.Migrations
{
    [DbContext(typeof(CardGameContext))]
    [Migration("20200602080128_AddImagesToHeroesMigration")]
    partial class AddImagesToHeroesMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.CardUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Armor");

                    b.Property<double>("Damage");

                    b.Property<int>("DamageType");

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<double>("Health");

                    b.Property<double>("HealthRegen");

                    b.Property<string>("Img");

                    b.Property<double>("Mana");

                    b.Property<double>("Manaregen");

                    b.Property<string>("Name");

                    b.Property<int>("Race");

                    b.HasKey("Id");

                    b.ToTable("CardUnits");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CardUnit");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("EffectType");

                    b.HasKey("Id");

                    b.ToTable("Effects");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Effect");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.HeroItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Img");

                    b.Property<string>("Name");

                    b.Property<Guid?>("SkillId");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("HeroItems");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.CardUnitSkills", b =>
                {
                    b.Property<Guid>("CardUnitId");

                    b.Property<Guid>("SkillId");

                    b.HasKey("CardUnitId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillSets");

                    b.HasData(
                        new { CardUnitId = new Guid("6f68fcfd-7cd6-4410-bc35-b7d96aa23969"), SkillId = new Guid("dd027abc-a8b9-4d89-b582-41c480c4fb45") },
                        new { CardUnitId = new Guid("6f68fcfd-7cd6-4410-bc35-b7d96aa23969"), SkillId = new Guid("e5e7bd4c-2be6-411c-a75c-81b4a8db86c3") },
                        new { CardUnitId = new Guid("038a0497-bf84-45cd-8fcc-22fd78bcafe1"), SkillId = new Guid("62ea4143-f6f3-4390-ac72-3e23561ed06b") },
                        new { CardUnitId = new Guid("038a0497-bf84-45cd-8fcc-22fd78bcafe1"), SkillId = new Guid("9bffe083-6bee-4a99-adcc-7d6cfbc8b59b") },
                        new { CardUnitId = new Guid("f6620430-3d02-4bae-9802-066434d03668"), SkillId = new Guid("f600f388-352a-4674-a533-1cc1347b7d61") },
                        new { CardUnitId = new Guid("f6620430-3d02-4bae-9802-066434d03668"), SkillId = new Guid("c68ed6dd-0479-47cb-810c-03e897990665") },
                        new { CardUnitId = new Guid("66e9be55-ffef-438a-9203-64a7a3062af7"), SkillId = new Guid("eb1d8e33-1cad-4f14-98c3-72938bad25fd") },
                        new { CardUnitId = new Guid("66e9be55-ffef-438a-9203-64a7a3062af7"), SkillId = new Guid("6ac2049f-151e-40bb-899e-0e836e0b6f5c") },
                        new { CardUnitId = new Guid("7129011f-bca0-4449-9629-3a46198267a1"), SkillId = new Guid("c03d9352-b51b-4d56-afe4-dfb2a32158a2") },
                        new { CardUnitId = new Guid("7129011f-bca0-4449-9629-3a46198267a1"), SkillId = new Guid("7ebeac14-4fac-4afb-9dc0-24fdc0c2fe39") },
                        new { CardUnitId = new Guid("e618edeb-ba86-449a-9602-896adb2db850"), SkillId = new Guid("147c6bc2-4e9b-4afc-b422-e0130252b1e0") },
                        new { CardUnitId = new Guid("e618edeb-ba86-449a-9602-896adb2db850"), SkillId = new Guid("cc4610f6-4f20-41d1-a529-522636674ff6") },
                        new { CardUnitId = new Guid("27f53ca1-3a40-4462-961d-d860547d8417"), SkillId = new Guid("8fb27632-30c5-4e4b-9925-c3594fe55c5a") },
                        new { CardUnitId = new Guid("484c6ca0-42c8-42ec-80ed-c919ef6f186c"), SkillId = new Guid("36478d6b-ac61-4c5a-af51-c649ff8851d2") },
                        new { CardUnitId = new Guid("484c6ca0-42c8-42ec-80ed-c919ef6f186c"), SkillId = new Guid("9572a874-9e78-4f3d-9964-5a25daf101d3") },
                        new { CardUnitId = new Guid("deb26782-8dd4-4d8e-9016-1202138b7b59"), SkillId = new Guid("c3414818-5b50-4da6-94e4-129339ccc21b") },
                        new { CardUnitId = new Guid("deb26782-8dd4-4d8e-9016-1202138b7b59"), SkillId = new Guid("b783a6d3-af5b-4b10-9f53-f3b05eb84aaf") },
                        new { CardUnitId = new Guid("b3c06915-0178-42de-a9bb-4369a41acfac"), SkillId = new Guid("eb1d8e33-1cad-4f14-98c3-72938bad25fd") },
                        new { CardUnitId = new Guid("b3c06915-0178-42de-a9bb-4369a41acfac"), SkillId = new Guid("00f75578-175e-40be-82b3-71e558041981") },
                        new { CardUnitId = new Guid("cc45d15c-a24a-4e04-9720-8e1e7841f6b4"), SkillId = new Guid("c6be27f6-3217-400f-9427-499d5719a5b6") },
                        new { CardUnitId = new Guid("cc45d15c-a24a-4e04-9720-8e1e7841f6b4"), SkillId = new Guid("7e4656e2-1440-46ee-a5e9-2438e359f33b") },
                        new { CardUnitId = new Guid("f9678bc4-bfe5-4bd9-a333-a0a93e943baa"), SkillId = new Guid("3a1a8de1-43b7-4dbe-861d-9c635e83df85") },
                        new { CardUnitId = new Guid("f9678bc4-bfe5-4bd9-a333-a0a93e943baa"), SkillId = new Guid("50fe62bf-979a-4ee7-9f12-b5313e00de98") },
                        new { CardUnitId = new Guid("9cae91c6-5213-4447-a4b3-458c2e4dd944"), SkillId = new Guid("4db2ba57-6f02-4c95-bf0a-f59af269fd3f") },
                        new { CardUnitId = new Guid("9cae91c6-5213-4447-a4b3-458c2e4dd944"), SkillId = new Guid("8fb27632-30c5-4e4b-9925-c3594fe55c5a") }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.SkillEffects", b =>
                {
                    b.Property<Guid>("SkillId");

                    b.Property<Guid>("EffectId");

                    b.Property<Guid>("TargetId");

                    b.HasKey("SkillId", "EffectId", "TargetId");

                    b.HasIndex("EffectId");

                    b.HasIndex("TargetId");

                    b.ToTable("SkillEffects");

                    b.HasData(
                        new { SkillId = new Guid("f600f388-352a-4674-a533-1cc1347b7d61"), EffectId = new Guid("eebe8f58-962c-4a81-8d9a-ea9c0b63d9d7"), TargetId = new Guid("46e167dc-52ad-4fbe-9950-967f55dc19c8") },
                        new { SkillId = new Guid("f600f388-352a-4674-a533-1cc1347b7d61"), EffectId = new Guid("03f7e71e-1729-4b24-a192-90c0470d83ed"), TargetId = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3") },
                        new { SkillId = new Guid("6ac2049f-151e-40bb-899e-0e836e0b6f5c"), EffectId = new Guid("16b9e7ba-239d-4c5b-a337-f3f78fff8065"), TargetId = new Guid("fb50a816-cd8d-4fd1-ba38-bf277dee7a1e") },
                        new { SkillId = new Guid("6ac2049f-151e-40bb-899e-0e836e0b6f5c"), EffectId = new Guid("44c83bc1-ecf8-4d19-b2cf-c608dcb4fe6a"), TargetId = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3") },
                        new { SkillId = new Guid("50fe62bf-979a-4ee7-9f12-b5313e00de98"), EffectId = new Guid("a4d29024-307a-4a9b-8fe1-8db09421d73a"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("50fe62bf-979a-4ee7-9f12-b5313e00de98"), EffectId = new Guid("1c021dbd-16a9-4146-b810-ff1d36211599"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("29c6ba61-a08f-4e32-9d46-77aa6c8f1478"), EffectId = new Guid("c5abb22c-394a-41a4-a1b7-df2ef3dfebc1"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("29c6ba61-a08f-4e32-9d46-77aa6c8f1478"), EffectId = new Guid("621a5b22-fcd1-43d5-9a5f-c3d35f6c631e"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("36478d6b-ac61-4c5a-af51-c649ff8851d2"), EffectId = new Guid("d436f5e5-d729-4d24-be7b-52e235b3bda8"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("87e38d0b-af62-439a-8cfa-febc53ac1b01"), EffectId = new Guid("ec381dc9-c1e5-47fb-8c57-51678224f07f"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("87e38d0b-af62-439a-8cfa-febc53ac1b01"), EffectId = new Guid("c5abb22c-394a-41a4-a1b7-df2ef3dfebc1"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("b783a6d3-af5b-4b10-9f53-f3b05eb84aaf"), EffectId = new Guid("915f8f7d-2a9d-4995-ae89-9d6f6e7bb40d"), TargetId = new Guid("7f0c2aa1-42ca-4b97-8371-7e7821a4a745") },
                        new { SkillId = new Guid("62ea4143-f6f3-4390-ac72-3e23561ed06b"), EffectId = new Guid("0feb5631-dd56-44b2-a207-00ee33551f09"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("62ea4143-f6f3-4390-ac72-3e23561ed06b"), EffectId = new Guid("1deaa57c-bc65-485e-8bb1-8d69aeeffa3d"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("9bffe083-6bee-4a99-adcc-7d6cfbc8b59b"), EffectId = new Guid("10076a8f-db65-4226-b910-cf6059cbe8d1"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("9bffe083-6bee-4a99-adcc-7d6cfbc8b59b"), EffectId = new Guid("ec381dc9-c1e5-47fb-8c57-51678224f07f"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("69bfd9cd-6c36-4637-8f17-6951cacb1204"), EffectId = new Guid("a4d29024-307a-4a9b-8fe1-8db09421d73a"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("cc4610f6-4f20-41d1-a529-522636674ff6"), EffectId = new Guid("a0c92644-5852-4a0d-884f-f27ca162fa0e"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("85d9908a-f79d-4586-9637-91c9de70983c"), EffectId = new Guid("ecaee0cf-bafa-4f21-8e6d-2e5fbd3cfe87"), TargetId = new Guid("799d2e51-f05c-4975-8a2b-99ddfeb8d9ca") },
                        new { SkillId = new Guid("8fb27632-30c5-4e4b-9925-c3594fe55c5a"), EffectId = new Guid("826bcba5-228b-4685-b454-5b233e2cd036"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("c3414818-5b50-4da6-94e4-129339ccc21b"), EffectId = new Guid("b12bbe16-3e81-4500-abb9-625f88e384f5"), TargetId = new Guid("636e0bb8-2876-4072-814f-1ab11e732e6c") },
                        new { SkillId = new Guid("c68ed6dd-0479-47cb-810c-03e897990665"), EffectId = new Guid("0feb5631-dd56-44b2-a207-00ee33551f09"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("c68ed6dd-0479-47cb-810c-03e897990665"), EffectId = new Guid("b1c4dd1a-d2cc-4f16-842e-c5b99bfcb4bd"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("dd027abc-a8b9-4d89-b582-41c480c4fb45"), EffectId = new Guid("460be20d-f644-4bc2-9286-7ead03b64e9c"), TargetId = new Guid("636e0bb8-2876-4072-814f-1ab11e732e6c") },
                        new { SkillId = new Guid("f50ade16-3b0e-4de4-af15-f268f075dd78"), EffectId = new Guid("874a9cf7-9719-4bbf-8e7f-30b4c77712e4"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("f50ade16-3b0e-4de4-af15-f268f075dd78"), EffectId = new Guid("d818f097-d830-4b3b-aaec-5abc73d5be59"), TargetId = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3") },
                        new { SkillId = new Guid("35c69f01-7c39-4324-aa6f-d550676229ad"), EffectId = new Guid("d5bd4c65-41a0-4bdc-a155-30d3d343b774"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("7ebeac14-4fac-4afb-9dc0-24fdc0c2fe39"), EffectId = new Guid("64e1a36b-d705-468f-8bfd-58d60d01a9a8"), TargetId = new Guid("646aa733-f4cf-4392-a339-2a067044d787") },
                        new { SkillId = new Guid("147c6bc2-4e9b-4afc-b422-e0130252b1e0"), EffectId = new Guid("15332b71-72f5-45b8-9027-263ce0328067"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("9572a874-9e78-4f3d-9964-5a25daf101d3"), EffectId = new Guid("3e8534bc-9679-4380-9034-1b9d62d6b8f5"), TargetId = new Guid("fb50a816-cd8d-4fd1-ba38-bf277dee7a1e") },
                        new { SkillId = new Guid("fc3e01a3-f6db-4912-b95c-ae10a4bc6832"), EffectId = new Guid("621a5b22-fcd1-43d5-9a5f-c3d35f6c631e"), TargetId = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3") },
                        new { SkillId = new Guid("fc3e01a3-f6db-4912-b95c-ae10a4bc6832"), EffectId = new Guid("265e0345-f383-4ac8-b33c-a4e20ee05faa"), TargetId = new Guid("375b43ef-65db-4b38-9708-66977db44e87") },
                        new { SkillId = new Guid("c03d9352-b51b-4d56-afe4-dfb2a32158a2"), EffectId = new Guid("85c2344e-22d7-42e2-aced-84c35c8eb13c"), TargetId = new Guid("a73a283d-a5fd-46cf-a95f-c03b05473295") },
                        new { SkillId = new Guid("7e4656e2-1440-46ee-a5e9-2438e359f33b"), EffectId = new Guid("16b9e7ba-239d-4c5b-a337-f3f78fff8065"), TargetId = new Guid("13d0b53a-c6ad-425c-a8c1-be7ae118e78a") },
                        new { SkillId = new Guid("c6be27f6-3217-400f-9427-499d5719a5b6"), EffectId = new Guid("80e4330a-1ec5-498d-b3b9-eb74cef24775"), TargetId = new Guid("13d0b53a-c6ad-425c-a8c1-be7ae118e78a") },
                        new { SkillId = new Guid("00f75578-175e-40be-82b3-71e558041981"), EffectId = new Guid("1deaa57c-bc65-485e-8bb1-8d69aeeffa3d"), TargetId = new Guid("952d3a54-9c70-4c2b-a657-20d077a62238") },
                        new { SkillId = new Guid("eb1d8e33-1cad-4f14-98c3-72938bad25fd"), EffectId = new Guid("1deaa57c-bc65-485e-8bb1-8d69aeeffa3d"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("6d241033-20da-4d9d-88db-d38551007304"), EffectId = new Guid("1a78deb7-c5d1-43de-be46-5945153a6aca"), TargetId = new Guid("253acb52-d5c6-4cd6-a8f8-974be5b6a91d") },
                        new { SkillId = new Guid("18ef20f2-b94d-4a3f-b38e-60d247a4c627"), EffectId = new Guid("aba933fd-0da7-41aa-a4fb-19e9f6a4e86e"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("18ef20f2-b94d-4a3f-b38e-60d247a4c627"), EffectId = new Guid("783a580c-8153-457c-847f-4e137c7e9b44"), TargetId = new Guid("a73a283d-a5fd-46cf-a95f-c03b05473295") },
                        new { SkillId = new Guid("e5e7bd4c-2be6-411c-a75c-81b4a8db86c3"), EffectId = new Guid("3e8534bc-9679-4380-9034-1b9d62d6b8f5"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("4db2ba57-6f02-4c95-bf0a-f59af269fd3f"), EffectId = new Guid("25b2142f-ad42-4f4c-9c3e-855e465b28a6"), TargetId = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9") },
                        new { SkillId = new Guid("3a1a8de1-43b7-4dbe-861d-9c635e83df85"), EffectId = new Guid("64e1a36b-d705-468f-8bfd-58d60d01a9a8"), TargetId = new Guid("0faafc79-6a2c-4506-b68a-d5c9ce226bdc") },
                        new { SkillId = new Guid("3a1a8de1-43b7-4dbe-861d-9c635e83df85"), EffectId = new Guid("04b17411-2761-465b-84cf-ac0e3589073d"), TargetId = new Guid("0faafc79-6a2c-4506-b68a-d5c9ce226bdc") }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Img");

                    b.Property<string>("Name");

                    b.Property<int>("Skillsort");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Skill");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("HeroTargetType");

                    b.Property<int>("TargetType");

                    b.HasKey("Id");

                    b.ToTable("Targets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Target");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Units.Hero", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.CardUnit");

                    b.Property<int>("ActionPoints");

                    b.Property<int>("HeroClass");

                    b.ToTable("Hero");

                    b.HasDiscriminator().HasValue("Hero");

                    b.HasData(
                        new { Id = new Guid("6f68fcfd-7cd6-4410-bc35-b7d96aa23969"), Armor = 5.0, Damage = 95.0, DamageType = 0, Description = "", Health = 300.0, HealthRegen = 25.0, Img = "BountyHunter.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Bounty Hunter", Race = 3, ActionPoints = 2, HeroClass = 4 },
                        new { Id = new Guid("038a0497-bf84-45cd-8fcc-22fd78bcafe1"), Armor = 8.0, Damage = 75.0, DamageType = 2, Description = "", Health = 600.0, HealthRegen = 35.0, Img = "ChaosKnight.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Chaos Knight", Race = 1, ActionPoints = 4, HeroClass = 5 },
                        new { Id = new Guid("f6620430-3d02-4bae-9802-066434d03668"), Armor = 3.0, Damage = 35.0, DamageType = 1, Description = "", Health = 300.0, HealthRegen = 15.0, Img = "CrystalMaiden.jpg", Mana = 5.0, Manaregen = 1.0, Name = "Crystal Maiden", Race = 0, ActionPoints = 1, HeroClass = 6 },
                        new { Id = new Guid("66e9be55-ffef-438a-9203-64a7a3062af7"), Armor = 5.0, Damage = 45.0, DamageType = 0, Description = "", Health = 450.0, HealthRegen = 50.0, Img = "Dazzle.jpg", Mana = 3.0, Manaregen = 1.0, Name = "Dazzle", Race = 5, ActionPoints = 3, HeroClass = 7 },
                        new { Id = new Guid("7129011f-bca0-4449-9629-3a46198267a1"), Armor = 2.0, Damage = 75.0, DamageType = 0, Description = "", Health = 300.0, HealthRegen = 20.0, Img = "DrowRanger.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Drow Ranger", Race = 4, ActionPoints = 1, HeroClass = 0 },
                        new { Id = new Guid("e618edeb-ba86-449a-9602-896adb2db850"), Armor = 4.0, Damage = 55.0, DamageType = 0, Description = "", Health = 300.0, HealthRegen = 15.0, Img = "Enchantress.jpg", Mana = 5.0, Manaregen = 1.0, Name = "Enchantress", Race = 3, ActionPoints = 1, HeroClass = 7 },
                        new { Id = new Guid("484c6ca0-42c8-42ec-80ed-c919ef6f186c"), Armor = 5.0, Damage = 60.0, DamageType = 0, Description = "", Health = 600.0, HealthRegen = 25.0, Img = "Juggernaut.jpg", Mana = 4.0, Manaregen = 0.5, Name = "Juggernaut", Race = 0, ActionPoints = 3, HeroClass = 1 },
                        new { Id = new Guid("deb26782-8dd4-4d8e-9016-1202138b7b59"), Armor = 3.0, Damage = 45.0, DamageType = 1, Description = "", Health = 450.0, HealthRegen = 25.0, Img = "Lich.jpg", Mana = 6.0, Manaregen = 2.0, Name = "Lich", Race = 4, ActionPoints = 2, HeroClass = 6 },
                        new { Id = new Guid("b3c06915-0178-42de-a9bb-4369a41acfac"), Armor = 1.0, Damage = 60.0, DamageType = 2, Description = "", Health = 400.0, HealthRegen = 10.0, Img = "QueenOfPain.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Queen Of Pain", Race = 1, ActionPoints = 3, HeroClass = 4 },
                        new { Id = new Guid("cc45d15c-a24a-4e04-9720-8e1e7841f6b4"), Armor = 3.0, Damage = 65.0, DamageType = 2, Description = "", Health = 400.0, HealthRegen = 10.0, Img = "ShadowFiend.jpg", Mana = 5.0, Manaregen = 0.5, Name = "Shadow Fiend", Race = 1, ActionPoints = 5, HeroClass = 2 },
                        new { Id = new Guid("f9678bc4-bfe5-4bd9-a333-a0a93e943baa"), Armor = 12.0, Damage = 85.0, DamageType = 0, Description = "", Health = 650.0, HealthRegen = 50.0, Img = "TrollWarlord.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Troll Warlord", Race = 5, ActionPoints = 4, HeroClass = 1 },
                        new { Id = new Guid("9cae91c6-5213-4447-a4b3-458c2e4dd944"), Armor = 6.0, Damage = 75.0, DamageType = 0, Description = "", Health = 550.0, HealthRegen = 45.0, Img = "Tusk.jpg", Mana = 3.0, Manaregen = 0.5, Name = "Tusk", Race = 3, ActionPoints = 2, HeroClass = 1 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Units.SummonUnit", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.CardUnit");


                    b.ToTable("SummonUnit");

                    b.HasDiscriminator().HasValue("SummonUnit");

                    b.HasData(
                        new { Id = new Guid("27f53ca1-3a40-4462-961d-d860547d8417"), Armor = 5.0, Damage = 1.0, DamageType = 0, Description = "", Health = 100.0, HealthRegen = 25.0, Img = "FearfulSigil.jpg", Mana = 1.0, Manaregen = 1.0, Name = "Fearful Sigil", Race = 7 },
                        new { Id = new Guid("dedb8175-0d78-4644-9ec9-eb0a7b8315a4"), Armor = 5.0, Damage = 1.0, DamageType = 0, Description = "", Health = 100.0, HealthRegen = 25.0, Img = "Nature'sAttendant.jpg", Mana = 1.0, Manaregen = 1.0, Name = "Nature's Attendant", Race = 6 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Amplify", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("Amount");

                    b.Property<int>("AmplifyType");

                    b.Property<int>("EffectState");

                    b.ToTable("Amplify");

                    b.HasDiscriminator().HasValue("Amplify");

                    b.HasData(
                        new { Id = new Guid("44c83bc1-ecf8-4d19-b2cf-c608dcb4fe6a"), Description = "", EffectType = 0, Amount = 5.0, AmplifyType = 5, EffectState = 0 },
                        new { Id = new Guid("b12bbe16-3e81-4500-abb9-625f88e384f5"), Description = "", EffectType = 0, Amount = 10.0, AmplifyType = 5, EffectState = 0 },
                        new { Id = new Guid("265e0345-f383-4ac8-b33c-a4e20ee05faa"), Description = "", EffectType = 0, Amount = 20.0, AmplifyType = 5, EffectState = 0 },
                        new { Id = new Guid("85c2344e-22d7-42e2-aced-84c35c8eb13c"), Description = "", EffectType = 0, Amount = 15.0, AmplifyType = 0, EffectState = 0 },
                        new { Id = new Guid("783a580c-8153-457c-847f-4e137c7e9b44"), Description = "", EffectType = 0, Amount = 25.0, AmplifyType = 0, EffectState = 0 },
                        new { Id = new Guid("a4d29024-307a-4a9b-8fe1-8db09421d73a"), Description = "", EffectType = 0, Amount = 50.0, AmplifyType = 0, EffectState = 0 },
                        new { Id = new Guid("715f2754-f78d-441f-9b94-4bc0946b1e67"), Description = "", EffectType = 0, Amount = 100.0, AmplifyType = 0, EffectState = 0 },
                        new { Id = new Guid("621a5b22-fcd1-43d5-9a5f-c3d35f6c631e"), Description = "", EffectType = 0, Amount = 250.0, AmplifyType = 1, EffectState = 0 },
                        new { Id = new Guid("0079b4f4-a17b-4326-ba40-f2e9753f0b23"), Description = "", EffectType = 0, Amount = 500.0, AmplifyType = 1, EffectState = 0 },
                        new { Id = new Guid("874a9cf7-9719-4bbf-8e7f-30b4c77712e4"), Description = "", EffectType = 0, Amount = 25.0, AmplifyType = 2, EffectState = 0 },
                        new { Id = new Guid("c5abb22c-394a-41a4-a1b7-df2ef3dfebc1"), Description = "", EffectType = 0, Amount = 50.0, AmplifyType = 2, EffectState = 0 },
                        new { Id = new Guid("f7f13521-0089-4759-9873-ebe96c46b4ca"), Description = "", EffectType = 0, Amount = 100.0, AmplifyType = 2, EffectState = 0 },
                        new { Id = new Guid("03f7e71e-1729-4b24-a192-90c0470d83ed"), Description = "", EffectType = 0, Amount = 5.0, AmplifyType = 3, EffectState = 0 },
                        new { Id = new Guid("df2f81c9-54cc-4ddf-ae55-eb59a664aa30"), Description = "", EffectType = 0, Amount = 10.0, AmplifyType = 3, EffectState = 0 },
                        new { Id = new Guid("d818f097-d830-4b3b-aaec-5abc73d5be59"), Description = "", EffectType = 0, Amount = 1.0, AmplifyType = 4, EffectState = 0 },
                        new { Id = new Guid("eebe8f58-962c-4a81-8d9a-ea9c0b63d9d7"), Description = "", EffectType = 0, Amount = 1.5, AmplifyType = 4, EffectState = 0 },
                        new { Id = new Guid("efbbfc8a-6bd7-46a8-8587-455005778bb4"), Description = "", EffectType = 0, Amount = 3.0, AmplifyType = 4, EffectState = 0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.CriticalHit", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("CriticalMultiplier");

                    b.Property<double>("CriticalProcChance");

                    b.Property<int>("DamageType");

                    b.ToTable("CriticalHit");

                    b.HasDiscriminator().HasValue("CriticalHit");

                    b.HasData(
                        new { Id = new Guid("aba933fd-0da7-41aa-a4fb-19e9f6a4e86e"), Description = "", EffectType = 3, CriticalMultiplier = 2.0, CriticalProcChance = 0.2, DamageType = 0 },
                        new { Id = new Guid("b5c330f2-23b4-4bf2-9481-55099367269c"), Description = "", EffectType = 3, CriticalMultiplier = 4.0, CriticalProcChance = 0.2, DamageType = 0 },
                        new { Id = new Guid("10076a8f-db65-4226-b910-cf6059cbe8d1"), Description = "", EffectType = 3, CriticalMultiplier = 4.0, CriticalProcChance = 0.2, DamageType = 2 },
                        new { Id = new Guid("d5bd4c65-41a0-4bdc-a155-30d3d343b774"), Description = "", EffectType = 3, CriticalMultiplier = 2.5, CriticalProcChance = 0.25, DamageType = 0 },
                        new { Id = new Guid("d436f5e5-d729-4d24-be7b-52e235b3bda8"), Description = "", EffectType = 3, CriticalMultiplier = 2.0, CriticalProcChance = 0.3, DamageType = 0 },
                        new { Id = new Guid("25b2142f-ad42-4f4c-9c3e-855e465b28a6"), Description = "", EffectType = 3, CriticalMultiplier = 2.5, CriticalProcChance = 1.0, DamageType = 0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.DealDamage", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("DamageAmount");

                    b.Property<int>("DamageType")
                        .HasColumnName("DealDamage_DamageType");

                    b.ToTable("DealDamage");

                    b.HasDiscriminator().HasValue("DealDamage");

                    b.HasData(
                        new { Id = new Guid("64e1a36b-d705-468f-8bfd-58d60d01a9a8"), Description = "", EffectType = 2, DamageAmount = 100.0, DamageType = 0 },
                        new { Id = new Guid("b1c4dd1a-d2cc-4f16-842e-c5b99bfcb4bd"), Description = "", EffectType = 2, DamageAmount = 150.0, DamageType = 1 },
                        new { Id = new Guid("1deaa57c-bc65-485e-8bb1-8d69aeeffa3d"), Description = "", EffectType = 2, DamageAmount = 150.0, DamageType = 2 },
                        new { Id = new Guid("80e4330a-1ec5-498d-b3b9-eb74cef24775"), Description = "", EffectType = 2, DamageAmount = 200.0, DamageType = 2 },
                        new { Id = new Guid("1dacb3a7-21f4-4439-b23d-c1e693084ee4"), Description = "", EffectType = 2, DamageAmount = 200.0, DamageType = 1 },
                        new { Id = new Guid("915f8f7d-2a9d-4995-ae89-9d6f6e7bb40d"), Description = "", EffectType = 2, DamageAmount = 300.0, DamageType = 1 },
                        new { Id = new Guid("e5af0d52-5663-44f2-b537-dace6d117229"), Description = "", EffectType = 2, DamageAmount = 300.0, DamageType = 2 },
                        new { Id = new Guid("3e8534bc-9679-4380-9034-1b9d62d6b8f5"), Description = "", EffectType = 2, DamageAmount = 300.0, DamageType = 0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Heal", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("HealAmount");

                    b.ToTable("Heal");

                    b.HasDiscriminator().HasValue("Heal");

                    b.HasData(
                        new { Id = new Guid("460be20d-f644-4bc2-9286-7ead03b64e9c"), Description = "", EffectType = 1, HealAmount = 75.0 },
                        new { Id = new Guid("1a78deb7-c5d1-43de-be46-5945153a6aca"), Description = "", EffectType = 1, HealAmount = 150.0 },
                        new { Id = new Guid("2d81259f-a7eb-4fa8-bfdb-613f93e6a9a4"), Description = "", EffectType = 1, HealAmount = 300.0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Lifesteal", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<double>("LifeStealPercentage");

                    b.ToTable("Lifesteal");

                    b.HasDiscriminator().HasValue("Lifesteal");

                    b.HasData(
                        new { Id = new Guid("ec381dc9-c1e5-47fb-8c57-51678224f07f"), Description = "", EffectType = 6, LifeStealPercentage = 0.25 },
                        new { Id = new Guid("55301e2e-9fb6-42cb-9973-498dc910fab1"), Description = "", EffectType = 6, LifeStealPercentage = 0.5 },
                        new { Id = new Guid("1c021dbd-16a9-4146-b810-ff1d36211599"), Description = "", EffectType = 6, LifeStealPercentage = 1.0 },
                        new { Id = new Guid("72ef6e9f-23a9-41c5-817d-3ba44b6ffc5f"), Description = "", EffectType = 6, LifeStealPercentage = 3.0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Reduce", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<int>("EffectState")
                        .HasColumnName("Reduce_EffectState");

                    b.Property<double>("ReduceAmount");

                    b.Property<int>("ReduceType");

                    b.ToTable("Reduce");

                    b.HasDiscriminator().HasValue("Reduce");

                    b.HasData(
                        new { Id = new Guid("16b9e7ba-239d-4c5b-a337-f3f78fff8065"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 5.0, ReduceType = 5 },
                        new { Id = new Guid("04b17411-2761-465b-84cf-ac0e3589073d"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 10.0, ReduceType = 5 },
                        new { Id = new Guid("6634567a-136f-4c81-af40-7b08aba8e5f4"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 15.0, ReduceType = 5 },
                        new { Id = new Guid("ecaee0cf-bafa-4f21-8e6d-2e5fbd3cfe87"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 50.0, ReduceType = 0 },
                        new { Id = new Guid("9faee829-0506-4e85-9892-decee6915dba"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 200.0, ReduceType = 1 },
                        new { Id = new Guid("b0c0f122-5310-4e9d-b809-c5727a6a11b0"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 400.0, ReduceType = 1 },
                        new { Id = new Guid("fddacf94-fb30-4476-be90-6c9ecd14c9c2"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 50.0, ReduceType = 2 },
                        new { Id = new Guid("16bde603-b191-4d96-a7fd-f5fb4609e357"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 100.0, ReduceType = 2 },
                        new { Id = new Guid("3fff91e9-8452-488f-bd23-26d3d308ab14"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 5.0, ReduceType = 3 },
                        new { Id = new Guid("8ed07187-66df-4d46-b1a0-1bdeb8dbacc8"), Description = "", EffectType = 8, EffectState = 1, ReduceAmount = 1.5, ReduceType = 4 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Silence", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<int>("EffectState")
                        .HasColumnName("Silence_EffectState");

                    b.Property<double>("SilenceDuration");

                    b.ToTable("Silence");

                    b.HasDiscriminator().HasValue("Silence");

                    b.HasData(
                        new { Id = new Guid("c650314d-e527-43ce-9932-5a6b01e7e309"), Description = "", EffectType = 4, EffectState = 1, SilenceDuration = 2.0 },
                        new { Id = new Guid("0025b00d-bbae-47ea-9d0d-e47f5c72ff3d"), Description = "", EffectType = 4, EffectState = 1, SilenceDuration = 4.0 },
                        new { Id = new Guid("f44a84c3-c6eb-42ec-9bb7-c69d9b6abdc0"), Description = "", EffectType = 4, EffectState = 1, SilenceDuration = 6.0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Stun", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<int>("EffectState")
                        .HasColumnName("Stun_EffectState");

                    b.Property<double>("StunDuration");

                    b.ToTable("Stun");

                    b.HasDiscriminator().HasValue("Stun");

                    b.HasData(
                        new { Id = new Guid("0feb5631-dd56-44b2-a207-00ee33551f09"), Description = "", EffectType = 7, EffectState = 1, StunDuration = 2.0 },
                        new { Id = new Guid("a0c92644-5852-4a0d-884f-f27ca162fa0e"), Description = "", EffectType = 7, EffectState = 1, StunDuration = 3.0 },
                        new { Id = new Guid("f7a3978f-30de-4d76-b087-e5146c788b6b"), Description = "", EffectType = 7, EffectState = 1, StunDuration = 4.0 },
                        new { Id = new Guid("4c7c8b0a-5409-41f9-a97d-00f3c7abc45b"), Description = "", EffectType = 7, EffectState = 1, StunDuration = 6.0 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Summon", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Effect");

                    b.Property<int>("AmountToSummon");

                    b.Property<Guid?>("SummonUnitId");

                    b.HasIndex("SummonUnitId");

                    b.ToTable("Summon");

                    b.HasDiscriminator().HasValue("Summon");

                    b.HasData(
                        new { Id = new Guid("826bcba5-228b-4685-b454-5b233e2cd036"), Description = "", EffectType = 5, AmountToSummon = 1, SummonUnitId = new Guid("27f53ca1-3a40-4462-961d-d860547d8417") },
                        new { Id = new Guid("15332b71-72f5-45b8-9027-263ce0328067"), Description = "", EffectType = 5, AmountToSummon = 7, SummonUnitId = new Guid("dedb8175-0d78-4644-9ec9-eb0a7b8315a4") }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Skills.ActiveSkill", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Skill");

                    b.Property<double>("Manacost");

                    b.ToTable("ActiveSkill");

                    b.HasDiscriminator().HasValue("ActiveSkill");

                    b.HasData(
                        new { Id = new Guid("50fe62bf-979a-4ee7-9f12-b5313e00de98"), Img = "BattleTrance.jpg", Name = "Battle Trance", Skillsort = 0, Manacost = 3.0 },
                        new { Id = new Guid("b783a6d3-af5b-4b10-9f53-f3b05eb84aaf"), Img = "ChainFrost.jpg", Name = "Chain Frost", Skillsort = 0, Manacost = 5.0 },
                        new { Id = new Guid("62ea4143-f6f3-4390-ac72-3e23561ed06b"), Img = "ChaosBolt.jpg", Name = "Chaos Bolt", Skillsort = 0, Manacost = 2.5 },
                        new { Id = new Guid("cc4610f6-4f20-41d1-a529-522636674ff6"), Img = "Enchant.jpg", Name = "Enchant", Skillsort = 0, Manacost = 2.0 },
                        new { Id = new Guid("8fb27632-30c5-4e4b-9925-c3594fe55c5a"), Img = "FearfulSigil.jpg", Name = "Fearful Sigil", Skillsort = 0, Manacost = 2.5 },
                        new { Id = new Guid("c3414818-5b50-4da6-94e4-129339ccc21b"), Img = "FrostArmor.jpg", Name = "Frost Armor", Skillsort = 0, Manacost = 2.0 },
                        new { Id = new Guid("c68ed6dd-0479-47cb-810c-03e897990665"), Img = "Frostbite.jpg", Name = "Frostbite", Skillsort = 0, Manacost = 3.0 },
                        new { Id = new Guid("147c6bc2-4e9b-4afc-b422-e0130252b1e0"), Img = "Nature'sAttendants.jpg", Name = "Nature's Attendants", Skillsort = 0, Manacost = 3.0 },
                        new { Id = new Guid("9572a874-9e78-4f3d-9964-5a25daf101d3"), Img = "Omnislash.jpg", Name = "Omnislash", Skillsort = 0, Manacost = 4.5 },
                        new { Id = new Guid("c03d9352-b51b-4d56-afe4-dfb2a32158a2"), Img = "PrecisionAura.jpg", Name = "Precision Aura", Skillsort = 0, Manacost = 2.0 },
                        new { Id = new Guid("c6be27f6-3217-400f-9427-499d5719a5b6"), Img = "RequiemOfSouls.jpg", Name = "Requiem Of Souls", Skillsort = 0, Manacost = 5.0 },
                        new { Id = new Guid("00f75578-175e-40be-82b3-71e558041981"), Img = "ScreamOfPain.jpg", Name = "Scream Of Pain", Skillsort = 0, Manacost = 2.5 },
                        new { Id = new Guid("eb1d8e33-1cad-4f14-98c3-72938bad25fd"), Img = "ShadowStrike.jpg", Name = "Shadow Strike", Skillsort = 0, Manacost = 1.5 },
                        new { Id = new Guid("6d241033-20da-4d9d-88db-d38551007304"), Img = "ShadowWave.jpg", Name = "Shadow Wave", Skillsort = 0, Manacost = 3.5 },
                        new { Id = new Guid("e5e7bd4c-2be6-411c-a75c-81b4a8db86c3"), Img = "ShurikenToss.jpg", Name = "Shuriken Toss", Skillsort = 0, Manacost = 2.5 },
                        new { Id = new Guid("4db2ba57-6f02-4c95-bf0a-f59af269fd3f"), Img = "WalrusPunch.jpg", Name = "Walrus Punch", Skillsort = 0, Manacost = 2.0 },
                        new { Id = new Guid("3a1a8de1-43b7-4dbe-861d-9c635e83df85"), Img = "WhirlingAxes.jpg", Name = "Whirling Axes", Skillsort = 0, Manacost = 2.5 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Skills.PassiveSkill", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Skill");


                    b.ToTable("PassiveSkill");

                    b.HasDiscriminator().HasValue("PassiveSkill");

                    b.HasData(
                        new { Id = new Guid("f600f388-352a-4674-a533-1cc1347b7d61"), Img = "ArcaneAura.jpg", Name = "Arcane Aura", Skillsort = 1 },
                        new { Id = new Guid("6ac2049f-151e-40bb-899e-0e836e0b6f5c"), Img = "BadJuju.jpg", Name = "Bad Juju", Skillsort = 1 },
                        new { Id = new Guid("29c6ba61-a08f-4e32-9d46-77aa6c8f1478"), Img = "BeautifulInside.jpg", Name = "Beautiful Inside", Skillsort = 1 },
                        new { Id = new Guid("36478d6b-ac61-4c5a-af51-c649ff8851d2"), Img = "BladeDance.jpg", Name = "Blade Dance", Skillsort = 1 },
                        new { Id = new Guid("87e38d0b-af62-439a-8cfa-febc53ac1b01"), Img = "BonAppetit.jpg", Name = "Bon Appetit", Skillsort = 1 },
                        new { Id = new Guid("9bffe083-6bee-4a99-adcc-7d6cfbc8b59b"), Img = "ChaosStrike.jpg", Name = "Chaos Strike", Skillsort = 1 },
                        new { Id = new Guid("69bfd9cd-6c36-4637-8f17-6951cacb1204"), Img = "DemonicAttack.jpg", Name = "Demonic Attack", Skillsort = 1 },
                        new { Id = new Guid("85d9908a-f79d-4586-9637-91c9de70983c"), Img = "FearfulAura.jpg", Name = "Fearful Aura", Skillsort = 1 },
                        new { Id = new Guid("dd027abc-a8b9-4d89-b582-41c480c4fb45"), Img = "HealingAttendant.jpg", Name = "Healing Attendant", Skillsort = 1 },
                        new { Id = new Guid("f50ade16-3b0e-4de4-af15-f268f075dd78"), Img = "HumanMind.jpg", Name = "Human Mind", Skillsort = 1 },
                        new { Id = new Guid("35c69f01-7c39-4324-aa6f-d550676229ad"), Img = "Jinada.jpg", Name = "Jinada", Skillsort = 1 },
                        new { Id = new Guid("7ebeac14-4fac-4afb-9dc0-24fdc0c2fe39"), Img = "Marksmanship.jpg", Name = "Marksmanship", Skillsort = 1 },
                        new { Id = new Guid("fc3e01a3-f6db-4912-b95c-ae10a4bc6832"), Img = "Orc'sFlesh.jpg", Name = "Orc's Flesh", Skillsort = 1 },
                        new { Id = new Guid("7e4656e2-1440-46ee-a5e9-2438e359f33b"), Img = "PresenceOfTheDarkLord.jpg", Name = "Presence Of The Dark Lord", Skillsort = 1 },
                        new { Id = new Guid("18ef20f2-b94d-4a3f-b38e-60d247a4c627"), Img = "SharpPaw.jpg", Name = "Sharp Paw", Skillsort = 1 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Targets.MultipleTarget", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Target");

                    b.Property<int>("AmountOfTargets");

                    b.Property<int>("AreaOfEffect");

                    b.ToTable("MultipleTarget");

                    b.HasDiscriminator().HasValue("MultipleTarget");

                    b.HasData(
                        new { Id = new Guid("646aa733-f4cf-4392-a339-2a067044d787"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 2, AreaOfEffect = 1 },
                        new { Id = new Guid("907b6938-1c4c-45dd-aa5c-c6be1c6965de"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 1 },
                        new { Id = new Guid("fb50a816-cd8d-4fd1-ba38-bf277dee7a1e"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 3 },
                        new { Id = new Guid("7f0c2aa1-42ca-4b97-8371-7e7821a4a745"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 5 },
                        new { Id = new Guid("952d3a54-9c70-4c2b-a657-20d077a62238"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 4, AreaOfEffect = 2 },
                        new { Id = new Guid("799d2e51-f05c-4975-8a2b-99ddfeb8d9ca"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 5, AreaOfEffect = 1 },
                        new { Id = new Guid("13d0b53a-c6ad-425c-a8c1-be7ae118e78a"), HeroTargetType = 2, TargetType = 0, AmountOfTargets = 99, AreaOfEffect = 99 },
                        new { Id = new Guid("11c5b5e5-60a7-4093-9c45-d3bb0acdb1df"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 1 },
                        new { Id = new Guid("08bf6141-fb84-47d1-a8e1-99b227c67ed3"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 3, AreaOfEffect = 3 },
                        new { Id = new Guid("253acb52-d5c6-4cd6-a8f8-974be5b6a91d"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 5, AreaOfEffect = 4 },
                        new { Id = new Guid("46e167dc-52ad-4fbe-9950-967f55dc19c8"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 5, AreaOfEffect = 4 },
                        new { Id = new Guid("0faafc79-6a2c-4506-b68a-d5c9ce226bdc"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 5, AreaOfEffect = 1 },
                        new { Id = new Guid("a73a283d-a5fd-46cf-a95f-c03b05473295"), HeroTargetType = 1, TargetType = 0, AmountOfTargets = 99, AreaOfEffect = 99 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Targets.SingleTarget", b =>
                {
                    b.HasBaseType("WBA.PE2.KurbanovD.Domain.Base.Target");


                    b.ToTable("SingleTarget");

                    b.HasDiscriminator().HasValue("SingleTarget");

                    b.HasData(
                        new { Id = new Guid("e21f9012-3037-4385-b0af-2d2eec3245b9"), HeroTargetType = 2, TargetType = 1 },
                        new { Id = new Guid("636e0bb8-2876-4072-814f-1ab11e732e6c"), HeroTargetType = 1, TargetType = 1 },
                        new { Id = new Guid("375b43ef-65db-4b38-9708-66977db44e87"), HeroTargetType = 0, TargetType = 1 }
                    );
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.HeroItem", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.CardUnitSkills", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.CardUnit", "CardUnit")
                        .WithMany("SkillSet")
                        .HasForeignKey("CardUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Skill", "Skill")
                        .WithMany("CardUnits")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Intermediates.SkillEffects", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Effect", "Effect")
                        .WithMany("Skills")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Skill", "Skill")
                        .WithMany("Effects")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Target", "Target")
                        .WithMany("SkillEffects")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WBA.PE2.KurbanovD.Domain.Base.Effects.Summon", b =>
                {
                    b.HasOne("WBA.PE2.KurbanovD.Domain.Base.Units.SummonUnit", "SummonUnit")
                        .WithMany()
                        .HasForeignKey("SummonUnitId");
                });
#pragma warning restore 612, 618
        }
    }
}
